### ISSUE TITLE
Scalar Evaluation

### ISSUE THREAD

**Issue by truephredd** [plagmada/plagmada-archives#19]
# Scalar http://scalar.usc.edu/scalar
## Critical
- [x] Can run in our hosting environment and/or AWS
- [x] Displays individual images
- [x] Displays metadata next to each image
- [ ] Metadata customizability
  - [ ]  Hidden Metadata (PII)
- [x]  Display Image Sets via Misc Criteria
- [ ] Batch Uploads of Images and associated Metadata
- [ ] Programming language/framework that volunteers are comfortable working with - _PHP/MySQL/JQuery_
- [x] High Capacity (20K+ images without straining)
- [x] Package used has Momentum & Stability
- [x] Admin UI is Well Designed
## Nice-to-have:
- [x] Licensing/Release Metadata Support
- [ ] Archiving vocabularies for certain fields.  EAD Compliant
- [ ] Potential to Release Our Bespoke Archiving Vocabularies to Wider Community
- [ ] Location vocabularies (GTGN?)
- [ ] Programming language/framework that volunteers enjoy
- [ ] Spoiler warnings, for individual artifacts
- [x] Open source - _ECL_
- [ ] Internationalizable/localizable
- [ ] Public users can upload their own work
- [ ] Public users can create tags for images
- [x] Mobile format?
## COSTING
- [x] FREE
- [ ] Modest Fee ( < $100/year)
- [ ] Immodest Fee (> $100/year)

**Comment by truephredd** [comment]
I am intrigued.

There's a lot of open questions after my first pass, so this one requires a deeper dig, but they have some online webinars that I'm going to go through.

**Comment by kwhite2** [comment]
I haven't worked with Scalar, but it could be a good tool for us, depending on what we find out from your second pass, Phredd. Keep us posted.

Krista

----- Original Message -----

**Comment by riverfr0zen** [comment]
(20K+ images without straining!) _Crawls from cave_ What is this? I want it!

**Comment by brainwane** [comment]
@truephredd The most critical question, I think, is how easy it would be to make Scalar accept batch uploads of Images and associated metadata.

**Comment by truephredd** [comment]
Noooooo! 

https://groups.google.com/forum/embed/?place=forum/scalar_support&theme=default&fragments=true&showsearch=true&showtabs=false&hideforumtitle=true&hidesubject=true&parenturl=http%3A%2F%2Fscalar.usc.edu%2Fscalar%2Fforums%2F#!searchin/scalar_support/upload/scalar_support/qVm1ySp7XBQ/2-oB2dYxBwAJ
