### ISSUE TITLE
S3 storage set up

### ISSUE THREAD

**Issue by riverfr0zen** [plagmada/plagmada-archives#2]
Set up Amazon S3 storage for plagmada and configure Omeka to save to S3

**Comment by truephredd** [comment]
@riverfr0zen What's the status here?

**Comment by riverfr0zen** [comment]
Wanted to upgrade to Omeka 2.4.1 before doing this. I just did that (upgrade), so I'll attack this next. Probably over the weekend. I don't foresee much of an issue (I've done it before), it's just a bunch of configuration I need to get around to.

**Comment by riverfr0zen** [comment]
I added documentation about the S3 setup. Would be kind of cool if you tried to follow that documentation. (That sounds rather aggressive, so let me note that: This is not a challenge about your system administration skills, Phredd, it is about whether I have any strengths in documentation).

The end result will be two-fold: 
- Omeka installation now uploading files to S3
- Secured bucket available for upload automation

**Comment by riverfr0zen** [comment]
Assigning to you, Phredd. I can probably do this by myself, but as I said earlier, it might be interesting if Phredd did it. Collaboration, different views, etc. etc. Does my documentation even read well and make sense?

**Comment by riverfr0zen** [comment]
The documentation is in the repository under /docs/s3_setup.md
https://github.com/plagmada/plagmada-archives/tree/master/docs

My hope is that things will be extremely well documented there.

**Comment by truephredd** [comment]
OK!  I'll check out the docs right now.  Then see about finding a time to work it this week.

-- Amending to say, I'm not good at reading docs right now.  :P  Will make some time to do this when I'm not distracted and faux multitasking.

**Comment by truephredd** [comment]
I am making an accountability post here.  I pledge to do the thing at some point this weekend.

**Comment by riverfr0zen** [comment]
Hey, absolutely no pressure there. If you can't get around to it, just let me know, and I'll do it. No worries at all.

**Comment by truephredd** [comment]
I should have plenty of time this weekend!  It's just motivationally helpful to put it up there and risk looking like a tool.

**Comment by riverfr0zen** [comment]
Anyway, if you do get lost with the documentation, don't hesitate to let me know. I wrote it pretty quickly and didn't proofread it too much.

**Comment by truephredd** [comment]
OK @riverfr0zen, completed the linkage to a staging bucket:

Filesystem                          Size  Used Avail Use% Mounted on
udev                                290M     0  290M   0% /dev
tmpfs                                59M   13M   47M  22% /run
/dev/disk/by-label/cloudimg-rootfs  7.8G  2.0G  5.4G  27% /
tmpfs                               294M     0  294M   0% /dev/shm
tmpfs                               5.0M     0  5.0M   0% /run/lock
tmpfs                               294M     0  294M   0% /sys/fs/cgroup
tmpfs                                59M     0   59M   0% /run/user/1000
s3fs                                256T     0  256T   0% /home/ubuntu/plagmada-archives/omeka-2.4.1/staging

**Comment by truephredd** [comment]
Should have closed this earlier, as it has been completed.
