### ISSUE TITLE
What's the workflow for public contributions with Omeka

### ISSUE THREAD

**Issue by riverfr0zen** [plagmada/plagmada-archives#5]
Discuss and establish desired workflow for the public (i.e. not an Omeka admin or curator)

**Comment by brainwane** [comment]
I agree -- it would be great to have an explanation of how you get your own work in there (can you scan it yourself? do you have to submit it by mail? are there any inclusion or exclusion criteria?).

**Comment by riverfr0zen** [comment]
Exactly. The response to this will also inform us as to what we need to build. For example, if we'd like people to upload the works themselves, then we'd have to build a 'public' uploader facing app. Maybe then there will need to be an interface through which admins move the public uploads to the plagmada actual archives (i.e. some kind of moderation workflow).

I think at the core of this question is: Do we want to engineer public-facing software for people to upload works into Omeka, or will this be handled by other means (email, snail mail, etc.). This could also be a future 'todo' item that we assign a lower priority to.

**Comment by brainwane** [comment]
My personal take is that, at least for 1.0 or launch, it's ok to only support the old workflow (users must mail paper to the Strong and then Tim scans it), and then in the future it's a good idea to make a moderated public upload process.

**Comment by truephredd** [comment]
Yes, that's kind of how the old workflow has worked, but not quite.

Items are generally delivered physically to Tim one way or another (snail mail, sneaker net).
Tim has a nice sheet fed scanner and does the scanning (or has a scanning party) to get things scanned in for upload to the website. 
This also serves to get things a bit sorted before shipping to strong.  Metal staples are removed so we can scan, etc.
When there's a critical mass of material, Tim posts it to the Strong.

I'm gonna poke Tim again to get him on Git, but he's in St. Louie visiting fams now, so I don't think has has aught but his phone ATM.

**Comment by truephredd** [comment]
I've considered buying a scanner myself, so there's one on each coast.

**Comment by kwhite2** [comment]
Agreed on supporting the old workflow for now.
